---
title: "PINNs - Escuela de Física Teórica de Valparaíso 2025"
format: html
---

<div style="text-align:center; font-family:sans-serif; line-height:1.6;">
  <h1 style="color:#F14925; font-size:2.5em; margin-bottom:0.3em;">
    Physics-Informed Neural Networks (PINNs)
  </h1>
  
  <p style="font-size:1.8em; margin:0.2em 0;">
    Juan Calles - <a href="mailto:juan.calles@uv.cl" style="color:inherit; text-decoration:none;">juan.calles@uv.cl</a>
  </p>
  
  <p style="font-size:1.5em; font-weight:bold; margin-top:1em;">
    Escuela de Física Teórica de Valparaíso
  </p>
  
  <p style="font-size:1.3em; margin:0.2em 0;">
    3 - 4 - 5 de Diciembre de 2025
  </p>
  <p style="font-size:1.3em; margin:0.2em 0;">
    Facultad de Ciencias y Edificio CIAE
  </p>
  <p style="font-size:1.3em; margin:0.2em 0;">
    Universidad de Valparaíso
  </p>
</div>


# Physics-Informed Neural Networks

Este sitio contiene el material de la clase sobre PINNs presentada en la Escuela de Física Teórica de Valparaíso 2025.

## Contenido

- [Introducción a PINNs](intro.ipynb)
- [Colab](colab.ipynb)
- [Hands-on session](PINN_notebook.ipynb)

## Objetivo

Aplicar métodos numéricos modernos de aprendizaje automático para resolver problemas físicos modelados mediante ecuaciones diferenciales parciales (EDPs).

## Cómo usar este sitio

Puedes navegar por las secciones desde la barra superior o usando los enlaces anteriores. Cada notebook está diseñado para ser autoexplicativo y ejecutable.

